version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8001:9000"  # Port modifié
    volumes:
      - .:/var/www
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8081:80"   # Port modifié
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
